// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plugins.DataStore.SQL;

namespace Plugins.DataStore.SQL.Migrations
{
    [DbContext(typeof(MarketContext))]
    [Migration("20220128165736_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreBusiness.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Categoria de Bebidas",
                            Name = "Bebidas"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Categoria de Panaderia",
                            Name = "Panaderia"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Categoria de Carnes",
                            Name = "Carnes"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Name = "Coca Cola",
                            Price = 3000.0,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Name = "Cerveza",
                            Price = 5000.0,
                            Quantity = 30
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Name = "Agua",
                            Price = 1500.0,
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Name = "Pan Tenza",
                            Price = 6500.0,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Name = "Tostadas Integrales",
                            Price = 3500.0,
                            Quantity = 25
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Name = "Pan Frances",
                            Price = 4500.0,
                            Quantity = 32
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Name = "Biffe Chorizo",
                            Price = 10500.0,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Name = "Solomo",
                            Price = 11000.0,
                            Quantity = 12
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Name = "Baby Beaf",
                            Price = 12000.0,
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("CoreBusiness.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BeforeQty")
                        .HasColumnType("int");

                    b.Property<string>("CashierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CoreBusiness.Product", b =>
                {
                    b.HasOne("CoreBusiness.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoreBusiness.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
