### Recuperar todas las peliculas
GET http://localhost:3100/movies

### Recuperar una pelicula por id
GET http://localhost:3100/movies/d017f713-63ce-11ee-95ef-b6fd202bf967

### Recuperar todas las pelicular po un genero
GET http://localhost:3100/movies?genre=action

### Crear una pelicula
POST http://localhost:3100/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
    "genre": [      
      "Crime",
      "Drama"
    ]
}

### Borrar una pelicula
DELETE http://localhost:3100/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3 


### Actualizar una pelicula
PATCH http://localhost:3100/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
Content-Type: application/json

{
    "year": 1992,
    "duration": 100
}

