@MyApi_HostAddress = http://localhost:5033

GET {{MyApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MyApi_HostAddress}}/Auth/Register/
Content-Type: application/json

{
  "UserName": "testuser2",
  "Password": "testPassword*10"
}