### Get Orders
GET http://localhost:31500/api/orders

### Get Order by Id
GET http://localhost:31500/api/orders/3

### Create a Order
POST http://localhost:31500/api/orders
Content-Type: application/json

{
    "Title": "Frizzer",
    "Quantity": 2,
    "Message": "Black",
    "City": "New York"
}

### Delete a Order
DELETE http://localhost:31500/api/orders/11

### Update a Order
PUT http://localhost:31500/api/orders
Content-Type: application/json

{
    "Id": 10,
    "Title": "Plasma TV",
    "Quantity": 6,
    "Message": "Sony Brand",
    "City": "New York"
}