// <auto-generated />
using System;
using BlazorSyncfusionCmr.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorSyncfusionCmr.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230516222339_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorSyncfusionCmr.Shared.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 5, 16, 17, 23, 39, 307, DateTimeKind.Local).AddTicks(6565),
                            DateOfBirth = new DateTime(2001, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Peter",
                            IsDeleted = false,
                            LastName = "Parker",
                            NickName = "Spider Man",
                            Place = "NYC"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 5, 16, 17, 23, 39, 307, DateTimeKind.Local).AddTicks(6582),
                            DateOfBirth = new DateTime(1975, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tony",
                            IsDeleted = false,
                            LastName = "Stark",
                            NickName = "Iron Man",
                            Place = "LA"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 5, 16, 17, 23, 39, 307, DateTimeKind.Local).AddTicks(6583),
                            DateOfBirth = new DateTime(1950, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Clark",
                            IsDeleted = false,
                            LastName = "Kent",
                            NickName = "Superman",
                            Place = "NYC"
                        });
                });

            modelBuilder.Entity("BlazorSyncfusionCmr.Shared.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactId = 1,
                            DateCreated = new DateTime(2023, 5, 16, 17, 23, 39, 307, DateTimeKind.Local).AddTicks(6698),
                            Text = "With great power comes great responsability"
                        },
                        new
                        {
                            Id = 2,
                            ContactId = 2,
                            DateCreated = new DateTime(2023, 5, 16, 17, 23, 39, 307, DateTimeKind.Local).AddTicks(6701),
                            Text = "I am Iron Man"
                        },
                        new
                        {
                            Id = 3,
                            ContactId = 3,
                            DateCreated = new DateTime(2023, 5, 16, 17, 23, 39, 307, DateTimeKind.Local).AddTicks(6702),
                            Text = "To the infinite"
                        });
                });

            modelBuilder.Entity("BlazorSyncfusionCmr.Shared.Note", b =>
                {
                    b.HasOne("BlazorSyncfusionCmr.Shared.Contact", "Contact")
                        .WithMany("Notes")
                        .HasForeignKey("ContactId");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("BlazorSyncfusionCmr.Shared.Contact", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
